name: Double Drops (Spigot 1.16.3+)
version: 1.0
author: MCHSoda
description: 2nd plugin, source code on github. Subscribe to MCHSoda on youtube for more info and totorials.
main: com.ffc.spigotplugins.mchsoda.doubledrops.Main